apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: care-nginx-production
  labels:
    application: care-nginx
    environment: production
    namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: care-nginx-production
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
